///array of objects
  export const data = [
    {
      "id": 0,
      "name": "American Wirehair",
      "imageUrl": "/img/guitar_cl_3.jpg",
      "style" : "Electric guitar",
      "price": "570 ₪",
      "brand" : "Fender",
    },
    {
      "id": 1,
      "name": "Cornish Rex",
      "imageUrl": "/img/guitar_ac_1.jpeg",
      "style": "Acoustic guitar",
      "price": "1890 ₪",
      "brand" : "Ibanez",
      },
    {
      "id": 2,
      "name": "Siamese",
      "imageUrl": "/img/guitar_cl_1.jpeg",
      "style": "Classic guitar",
      "price": "780 ₪",
      "brand" : "Takamine",
      },
    {
      "id": 3,
      "name": "British Shorthair",
      "imageUrl": "/img/guitar_el_3.jpg",
      "style": "Electric guitar",
      "price": "2570 ₪",
      "brand" : "Cort",
      },
    {
      "id": 4,
      "name": "Persian",
      "imageUrl": "/img/guitar_el_1.jpeg",
      "style": "Acoustic guitar",
      "price": "1560 ₪",
      "brand" : "Asmo",
      },
    {
        "id": 5,
        "name": "American Wirehair",
        "imageUrl": "/img/guitar_cl_3.jpg",
        "style" : "Electric guitar",
        "price": "570 ₪",
        "brand" : "Fender",
      },
    {
        "id": 6,
        "name": "Cornish Rex",
        "imageUrl": "/img/guitar_ac_1.jpeg",
        "style": "Acoustic guitar",
        "price": "1890 ₪",
        "brand" : "Ibanez",
        },
    {
        "id": 7,
        "name": "Siamese",
        "imageUrl": "/img/guitar_cl_1.jpeg",
        "style": "Classic guitar",
        "price": "780 ₪",
        "brand" : "Takamine",
        },
    {
        "id": 8,
        "name": "British Shorthair",
        "imageUrl": "/img/guitar_el_3.jpg",
        "style": "Electric guitar",
        "price": "2570 ₪",
        "brand" : "Cort",
        },
    {
        "id": 9,
        "name": "Stratocaster H345",
        "imageUrl": "/img/guitar_el_4.jpg",
        "style": "Electric guitar",
        "price": "2560 ₪",
        "brand" : "Fender",
        },
    {
        "id": 10,
        "name": "Stratocaster H345",
        "imageUrl": "/img/guitar_el_3.jpg",
        "style": "Electric guitar",
        "price": "1560 ₪",
        "brand" : "Asmo",
        },
    {
      "id": 11,
      "name": "American Wirehair",
      "imageUrl": "/img/guitar_cl_3.jpg",
      "style" : "Electric guitar",
      "price": "570 ₪",
      "brand" : "Fender",
    },
    {
      "id": 12,
      "name": "Cornish Rex",
      "imageUrl": "/img/guitar_ac_1.jpeg",
      "style": "Acoustic guitar",
      "price": "1890 ₪",
      "brand" : "Ibanez",
      },
    {
      "id": 13,
      "name": "Siamese",
      "imageUrl": "/img/guitar_cl_1.jpeg",
      "style": "Classic guitar",
      "price": "780 ₪",
      "brand" : "Takamine",
      },
    {
      "id": 14,
      "name": "British Shorthair",
      "imageUrl": "/img/guitar_el_3.jpg",
      "style": "Electric guitar",
      "price": "2570 ₪",
      "brand" : "Cort",
      },
    {
      "id": 15,
      "name": "Persian",
      "imageUrl": "/img/guitar_el_1.jpeg",
      "style": "Acoustic guitar",
      "price": "1560 ₪",
      "brand" : "Asmo",
      },
    {
        "id": 16,
        "name": "American Wirehair",
        "imageUrl": "/img/guitar_cl_3.jpg",
        "style" : "Electric guitar",
        "price": "570 ₪",
        "brand" : "Fender",
      },
    {
        "id": 17,
        "name": "Cornish Rex",
        "imageUrl": "/img/guitar_ac_1.jpeg",
        "style": "Acoustic guitar",
        "price": "1890 ₪",
        "brand" : "Ibanez",
        },
    {
        "id": 18,
        "name": "Siamese",
        "imageUrl": "/img/guitar_cl_1.jpeg",
        "style": "Classic guitar",
        "price": "780 ₪",
        "brand" : "Takamine",
        },
    {
        "id": 19,
        "name": "British Shorthair",
        "imageUrl": "/img/guitar_el_3.jpg",
        "style": "Electric guitar",
        "price": "2570 ₪",
        "brand" : "Cort",
        },
    {
        "id": 20,
        "name": "Stratocaster H345",
        "imageUrl": "/img/guitar_el_4.jpg",
        "style": "Electric guitar",
        "price": "2560 ₪",
        "brand" : "Fender",
        },
    {
        "id": 21,
        "name": "Stratocaster H345",
        "imageUrl": "/img/guitar_el_3.jpg",
        "style": "Electric guitar",
        "price": "1560 ₪",
        "brand" : "Asmo",
        },
    {
      "id": 22,
      "name": "American Wirehair",
      "imageUrl": "/img/guitar_cl_3.jpg",
      "style" : "Electric guitar",
      "price": "570 ₪",
      "brand" : "Fender",
    },
    {
      "id": 23,
      "name": "Cornish Rex",
      "imageUrl": "/img/guitar_ac_1.jpeg",
      "style": "Acoustic guitar",
      "price": "1890 ₪",
      "brand" : "Ibanez",
      },
    {
      "id": 24,
      "name": "Siamese",
      "imageUrl": "/img/guitar_cl_1.jpeg",
      "style": "Classic guitar",
      "price": "780 ₪",
      "brand" : "Takamine",
      },
    {
      "id": 25,
      "name": "British Shorthair",
      "imageUrl": "/img/guitar_el_3.jpg",
      "style": "Electric guitar",
      "price": "2570 ₪",
      "brand" : "Cort",
      },
    {
      "id": 26,
      "name": "Persian",
      "imageUrl": "/img/guitar_el_1.jpeg",
      "style": "Acoustic guitar",
      "price": "1560 ₪",
      "brand" : "Asmo",
      },
    {
        "id": 27,
        "name": "American Wirehair",
        "imageUrl": "/img/guitar_cl_3.jpg",
        "style" : "Electric guitar",
        "price": "570 ₪",
        "brand" : "Fender",
      },
    {
        "id": 28,
        "name": "Cornish Rex",
        "imageUrl": "/img/guitar_ac_1.jpeg",
        "style": "Acoustic guitar",
        "price": "1890 ₪",
        "brand" : "Ibanez",
        },
    {
        "id": 29,
        "name": "Siamese",
        "imageUrl": "/img/guitar_cl_1.jpeg",
        "style": "Classic guitar",
        "price": "780 ₪",
        "brand" : "Takamine",
        },
    {
        "id": 30,
        "name": "British Shorthair",
        "imageUrl": "/img/guitar_el_3.jpg",
        "style": "Electric guitar",
        "price": "2570 ₪",
        "brand" : "Cort",
        },
    {
        "id": 31,
        "name": "Stratocaster H345",
        "imageUrl": "/img/guitar_el_4.jpg",
        "style": "Electric guitar",
        "price": "2560 ₪",
        "brand" : "Fender",
        },
    {
        "id": 32,
        "name": "Stratocaster H345",
        "imageUrl": "/img/guitar_el_3.jpg",
        "style": "Electric guitar",
        "price": "1560 ₪",
        "brand" : "Asmo",
        }
  ];